export enum CityActionTypes {
    GET_CITY_BY_NAME = 'GET_CITY_BY_NAME',
    ADD_CITY_IN_LIST = 'ADD_CITY_IN_LIST',
    GET_WEATHER_BY_CITY_ID = 'GET_WEATHER_BY_CITY_ID',
    REMOVE_CITY_FROM_LIST = 'REMOVE_CITY_FROM_LIST',
}